name: ${project.name}
description: ${project.description}
main: com.johnymuffin.serverinformation.beta.JServerInformation
version: ${project.version}
authors:
  - JohnyMuffin
softdepend:
  - Fundamentals
  - JWebAPI