name: ${project.name}
description: ${project.description}
main: com.johnymuffin.serverinformation.beta.JServerInformation
version: ${project.version}
authors:
  - JohnyMuffin
softdepend:
  - Fundamentals
  - JWebAPI
commands:
  hidecoords:
    description: Hide your coordinates from the server information API.
    usage: /<command> [on|off|status]
    aliases:
      - hidecoordinates
permissions:
  jserverinformation.hidecoords:
    description: Allows players to hide their coordinates from the server information API.
    default: true
